version: '3.9'

services:
  db:
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5423
  app:
    container_name: chat-app-app_prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PWD}@localhost:5432/${DB_NAME}
    command: npm run build && npm run start:prod
