version: '3.9'

services:
  db:
    environment:
      - DB_PATH=${DB_PATH}
    volumes:
      - ${DB_PATH}:/data/db
    ports:
      - '27020-27023:27020-27023'

  app:
    container_name: auth-nest-app_dev
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://${DB_USER}:${DB_PWD}@auth-nest-db:27020/${DB_NAME}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm run start:dev
