version: '3.9'

services:
  db:
    image: postgres
    container_name: chat-app-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '${APP_PORT}'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
