version: '3.9'

services:
  db:
    image: postgres:13
    container_name: chat-app-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '${APP_PORT}'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    restart: unless-stopped
  pgadmin:
    container_name: chat-app-pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
     - ${PGADMIN_DATA_PATH}:/var/lib/pgadmin
