version: '3.9'

services:
  db:
    image: mongo
    container_name: auth-nest-db
    volumes:
      - /auth-nest/data/db
    ports:
      - '27031:27017'
    expose:
      - '27017'
  app:
    container_name: auth-nest-app_prod
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://${DB_USER}:${DB_PWD}@auth-nest-db:27017/${DB_NAME}
    command: npm run start:prod
