version: '3.9'

services:
  db:
    environment:
      - DB_PATH=${DB_PATH}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    container_name: chat-app-app_dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PWD}@chat-app-db:5432/${DB_NAME}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: bash -c 'sh ./wait-for-postgres.sh npx prisma migrate deploy && npm run prisma:seed:force && npm run start:dev'
