export enum ChatIncomingEvents {
    SEND_MESSAGE_TO_SERVER = 'CHAT/SEND_MESSAGE_TO_SERVER',
    CLIENT_JOIN_ROOM = 'CHAT/CLIENT_JOIN_ROOM',
    CLIENT_LEAVE_ROOM = 'CHAT/CLIENT_LEAVE_ROOM',
}

export enum ChatOutgoingEvents {
    SEND_MESSAGE_TO_CLIENT = 'CHAT/SEND_MESSAGE_TO_CLIENT',
    CLIENT_JOINED_ROOM = 'CHAT/CLIENT_JOINED_ROOM',
    CLIENT_LEAVED_ROOM = 'CHAT/CLIENT_LEAVED_ROOM',
}
