FROM python:3.9.7-buster as setup

WORKDIR /

# Upgrade pip
RUN pip3 install --upgrade pip

ARG USER=nobody
RUN usermod -aG sudo $USER


FROM setup as libs

COPY requirements.api-only.txt .

RUN pip3 --no-cache-dir install -r requirements.api-only.txt


FROM libs as app
RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY . .
CMD ["/bin/bash"]
